STORAGE_DIR: /sdf/data/neutrino/$USER/dunend_train_prod/flow2supera
SINGULARITY_IMAGE: /sdf/group/neutrino/images/larcv2_ub20.04-cuda11.6-pytorch1.13-larndsim-2023-11-07.sif
STORE_IMAGE: False
SLURM_WORK_DIR:  $LSCRATCH/$USER
SLURM_NUM_JOBS:  1        # number of jobs to submit
SLURM_PARTITION: ampere   # partition
SLURM_ACCOUNT:   neutrino:dune-ml # account
SLURM_TIME:      1:00:00 # max time HH:MM:SS
SLURM_MEM:       24       # total in GB
SLURM_CPU:       6        # number of CPUs
SLURM_NODELIST: ''
SLURM_EXCLUDE:  ''

# larnd2supera config
SUPERA_CONFIG: 2x2
GLOB: "/sdf/data/neutrino/$USER/dunend_train_prod/prod2x2_mlreco_mpvmpr_v0_2/production_3627898/job_41421128_0005/output_41421128_0005-flow.h5"
