# ===============
# mpvmpr_cfg.yaml
# ===============

# 2x2 geometry boundaries in mm
# 
# X: -639.31 => 639.31
# Y: -198.543 => 1038.543
# Z: -643.163 => 643.163
#
# geo_v4
# X: -639.31 => 639.31
# Y: -618.543 => 618.543
# Z: -643.163 => 643.163

SEED: -1
## with lepton, generate 4cm from the wall
Generator1:
  NumEvent: [1,2]
  NumParticle: [1,8]
  #  XRange: [-679.31,679.31] #mm
  #  YRange: [-2418.543,-1261.457] # [-158,543,998.543] #mm
  #  ZRange: [12396.837,13603.163] # [-603.163,604.163] #mm
  XRange: [-599.31,599.31] #mm
  YRange: [-578.543,578.543] #mm
  #YRange: [-158.543,998.543] #mm
  ZRange: [-603.163,603.163] #mm
  TRange: [0,10000] #ns
  AddParent: True
  Particles:
    -
      PDG:      [11,-11,13,-13]
      NumRange: [1,1]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   1
    -
      PDG:      [211,-211]
      NumRange: [0,2]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [22,111]
      NumRange: [0,2]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [2212]
      NumRange: [0,5]
      KERange:  [0.02,3.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [2112]
      NumRange: [0,2]
      KERange:  [0.02,3.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [130, 321, -321, 310]
      NumRange: [0,1]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   0.25

    -
      PDG:      [3122]
      NumRange: [0,1]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   0.25

# NC
Generator2:
  NumEvent: [0,1]
  NumParticle: [1,7]
  XRange: [-599.31,599.31] #mm
  YRange: [-578.543,578.543] #mm
  ZRange: [-603.163,604.163] #mm
  TRange: [0,10000] #ns
  AddParent: True
  Particles:
    -
      PDG:      [211,-211]
      NumRange: [0,2]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [22,111]
      NumRange: [0,2]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [2212]
      NumRange: [0,5]
      KERange:  [0.02,3.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [2112]
      NumRange: [0,2]
      KERange:  [0.02,3.]
      UseMom:   True
      Weight:   1

    -
      PDG:      [130, 321, -321, 310]
      NumRange: [0,1]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   0.25

    -
      PDG:      [3122]
      NumRange: [0,1]
      KERange:  [0.01,4.]
      UseMom:   True
      Weight:   0.25

Singles:
  NumEvent: [1,5]
  NumParticle: [1,1]
  #XRange: [-679.31,679.31] #mm
  #YRange: [-2418.543,-1261.457] # [-158,543,998.543] #mm
  #ZRange: [12396.837,13603.163] # [-603.163,604.163] #mm
  XRange: [-679.31,679.31] #mm
  YRange: [-658.543,658.543] #mm
  #YRange: [-238.543,1078.543] #mm
  ZRange: [-683.163,683.163] #mm
  TRange: [0,10000] #ns
  Particles:
    -
      PDG:  [13, -13]
      NumRange: [0,1]
      KERange:  [0.05,4.]
      UseMom:   True
      Weight:   1

    -
      PDG:  [-13]
      NumRange: [0,1]
      KERange:  [0.075,0.25]
      UseMom:   True
      Weight:   1

    -
      PDG:  [22]
      NumRange: [0,1]
      KERange:  [0.01,1.]
      UseMom:   True
      Weight:   0.5

    -
      PDG:  [211,-211]
      NumRange: [0,1]
      KERange:  [0.05,1.]
      UseMom:   True
      Weight:   0.5

    -
      PDG:  [2212]
      NumRange: [0,1]
      KERange:  [0.05,1.]
      UseMom:   True
      Weight:   0.5

    -
      PDG:  [2112]
      NumRange: [0,1]
      KERange:  [0.05,0.5]
      UseMom:   True
      Weight:   0.25
