SEED: -1
GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [300,310]
  YRange: [-830,400]
  ZRange: [-300,300]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [-13]
      NumRange: [1,1]
      KERange:  [0.05, 0.2]
      UseMom:   False
      Weight:   1

GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [-310,-300]
  YRange: [-830,400]
  ZRange: [-300,300]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [-13]
      NumRange: [1,1]
      KERange:  [0.05,0.2]
      UseMom:   False
      Weight:   1
      
GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [-300,300]
  YRange: [-840,-830]
  ZRange: [-300,300]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [-13]
      NumRange: [1,1]
      KERange:  [0.05, 0.2]
      UseMom:   False
      Weight:   1

GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [-300,300]
  YRange: [400,410]
  ZRange: [-300,300]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [-13]
      NumRange: [1,1]
      KERange:  [0.05, 0.2]
      UseMom:   False
      Weight:   1

GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [-300,300]
  YRange: [-830,400]
  ZRange: [-310,-300]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [-13]
      NumRange: [1,1]
      KERange:  [0.05, 0.2]
      UseMom:   False
      Weight:   1

GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [-300,300]
  YRange: [-830,400]
  ZRange: [300,310]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [-13]
      NumRange: [1,1]
      KERange:  [0.05, 0.2]
      UseMom:   False
      Weight:   1
