SEED: -1
GeneratorMPV:
  NumEvent: [1,1]
  NumParticle: [1,1]
  XRange: [-280,280]
  YRange: [-810,380]
  ZRange: [-280,280]
  TRange: [0,1]
  AddParent: True
  Particles:
    -
      PDG:      [13]
      NumRange: [1,1]
      KERange:  [0.05, 0.3]
      UseMom:   True
      Weight:   1
