SINGULARITY_IMAGE: /sdf/group/neutrino/images/larcv2_ub20.04-cuda11.6-pytorch1.13-larndsim-2023-11-07.sif
STORAGE_DIR: /sdf/data/neutrino/$USER/dunend_train_prod/prod2x2_mlreco_mpvmpr_v0_5
JOB_WORK_DIR:  $LSCRATCH/$USER
SLURM_CONFIG: slurm_s3df_august2024_stage1.yaml

#SHIFTER_IMAGE: deeplearnphysics/larcv2:ub20.04-cuda11.6-pytorch1.13-larndsim 
#STORAGE_DIR: /global/cfs/cdirs/m4617/$USER/dunend_train_prod/prod2x2_mlreco_mpvmpr_v0_4
#JOB_WORK_DIR:  $PSCRATCH/$USER
#SLURM_CONFIG: slurm_perlmutter_flow.yaml

STORE_IMAGE: False
TIERS: ['flow','flow2supera']
#INPUT_FILES: flist.txt
INPUT_FILES: flist_53106321.txt


#
# ndlar-flow
#

FLOW_REPOSITORY: modules/ndlar_flow
SEARCH_FLOW_YAML: yamls
SEARCH_FLOW_DATA: data


#
# flow2supera
#
LARCV_DIR: /sdf/group/neutrino/kterao/sw/test/modules/larcv2
SUPERA_CONFIG: 2x2_mpvmpr