STORAGE_DIR: /sdf/data/neutrino/$USER/dunend_train_prod/prod2x2_v0_4_flow2supera
JOB_WORK_DIR:  $LSCRATCH/$USER
SINGULARITY_IMAGE: /sdf/group/neutrino/images/larcv2_ub20.04-cuda11.6-pytorch1.13-larndsim-2023-11-07.sif
STORE_IMAGE: False
SLURM_CONFIG: slurm_s3df_flow2supera.yaml
SLURM_ARRAY: 1%1

LARCV_DIR: /global/common/software/m4617/$USER/dunend_train_prod/modules/larcv2

# flow2supera config (this config requirement should be removed from flow2supera)
SUPERA_CONFIG: 2x2_mpvmpr

GLOB: "/sdf/data/neutrino/cyifan/dunend_train_prod/prod2x2_mlreco_mpvmpr_v0_4/production_1694956/job_51665434_0001/output_51665434_0001-flow.h5"
