STORAGE_DIR: /sdf/data/neutrino/$USER/dunend_train_prod/prod2x2_v0_1_larnd2supera
SINGULARITY_IMAGE: /sdf/group/neutrino/images/larcv2_ub20.04-cuda11.6-pytorch1.13-larndsim.sif
STORE_IMAGE: False

SLURM_WORK_DIR:  $LSCRATCH/$USER
SLURM_PARTITION: ampere   # partition
SLURM_TIME:      20:00:00 # max time HH:MM:SS
SLURM_MEM:       24       # total in GB
SLURM_CPU:       6        # number of CPUs
SLURM_NODELIST: ''
SLURM_EXCLUDE:  ''

# larnd2supera config
SUPERA_CONFIG: 2x2

#SLURM_NUM_JOBS: 132%40
#GLOB: "/sdf/data/neutrino/kterao/dunend_train_prod/prod2x2_v0_1/production_828284/job_17842428_0*/output*larndsim.h5"
#SLURM_NUM_JOBS: 176%40
#GLOB: "/sdf/data/neutrino/kterao/dunend_train_prod/prod2x2_v0_1/production_[3467]*/job_*/*larndsim.h5"
#SLURM_NUM_JOBS: 108%40
#GLOB: "/sdf/data/neutrino/kterao/dunend_train_prod/prod2x2_v0_1/production_994062/job_1*/output*larndsim.h5"
SLURM_NUM_JOBS: 157%40
GLOB: "/sdf/data/neutrino/kterao/dunend_train_prod/prod2x2_v0_1/production_1133554/job_1*/*larndsim.h5"