SLURM_PARTITION: ampere   # partition
SLURM_ACCOUNT:   neutrino:dune-ml # account
SLURM_TIME:      5:00:00 # max time HH:MM:SS
SLURM_MEM-PER-CPU: 4G
SLURM_CPUS-PER-TASK: 6
SLURM_NODELIST: ''
SLURM_EXCLUDE:  ''
SLURM_NODES: 1
SLURM_NTASKS: 1